const employeeActionTypes = {
    SET_LISTEMPLOYEE: "SET_LISTEMPLOYEE",
    SET_LISTEMPLOYEE_SUCCESS: "SET_LISTEMPLOYEE_SUCCESS",

    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
    ADD_EMPLOYEE_ERROR: "ADD_EMPLOYEE_ERROR",

    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
    UPDATE_EMPLOYEE_ERROR: "UPDATE_EMPLOYEE_ERROR",

    DEL_EMPLOYEE: "DEL_EMPLOYEE",
    DEL_EMPLOYEE_SUCCESS: "DEL_EMPLOYEE_SUCCESS",
    DEL_EMPLOYEE_ERROR: "DEL_EMPLOYEE_ERROR",
};

export default employeeActionTypes;